export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const IMAGE_UPLOAD_SUSSESS = "IMAGE_UPLOAD_SUSSESS";
export const IMAGE_UPLOAD_ERROR = "IMAGE_UPLOAD_ERROR";

export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE";

export const GET_TIMECARDS = "GET_TIMECARDS";
export const GET_TIMECARD = "GET_TIMECARD";
export const TIMECARDS_ERROR = "TIMECARDS_ERROR";

export const CREATE_TIMECARD = "CREATE_TIMECARD";
export const TIMECARDS_ERR_MSG = "TIMECARDS_ERR_MSG";
export const GET_TIMECARD_HOURS = "GET_TIMECARD_HOURS";
export const DELETE_TIMECARD = "DELETE_TIMECARD";
export const UPDATE_TIMECARD = "UPDATE_TIMECARD";
export const APPROVE_TIMECARD = "APPROVE_TIMECARD";

export const CREATE_TIMECARD_HOURS = "CREATE_TIMECARD_HOURS";
export const CREATE_TIMECARD_TUESDAY_HOURS = "CREATE_TIMECARD_TUESDAY_HOURS";
export const CREATE_TIMECARD_WENDSDAY_HOURS = "CREATE_TIMECARD_WENDSDAY_HOURS";
export const CREATE_TIMECARD_THURSDAY_HOURS = "CREATE_TIMECARD_THURSDAY_HOURS";
export const CREATE_TIMECARD_FRIDAY_HOURS = "CREATE_TIMECARD_FRIDAY_HOURS";
export const CREATE_TIMECARD_SATARDAY_HOURS = "CREATE_TIMECARD_SATARDAY_HOURS";
export const CREATE_TIMECARD_SUNDAY_HOURS = "CREATE_TIMECARD_SUNDAY_HOURS";

export const DELETE_MONDAY_TIMECARD_HOURS = "DELETE_MONDAY_TIMECARD_HOURS";
export const DELETE_TUESDAY_TIMECARD_HOURS = "DELETE_TUESDAY_TIMECARD_HOURS";
export const DELETE_WENDSDAY_TIMECARD_HOURS = "DELETE_WENDSDAY_TIMECARD_HOURS";
export const DELETE_THURSDAY_TIMECARD_HOURS = "DELETE_THURSDAY_TIMECARD_HOURS";
export const DELETE_FRIDAY_TIMECARD_HOURS = "DELETE_FRIDAY_TIMECARD_HOURS";
export const DELETE_SATARDAY_TIMECARD_HOURS = "DELETE_SATARDAY_TIMECARD_HOURS";
export const DELETE_SUNDAY_TIMECARD_HOURS = "DELETE_SUNDAY_TIMECARD_HOURS";

export const SEARCH_TIMECARD = "SEARCH_TIMECARD";
export const ORDER_TIMECARD = "ORDER_TIMECARD";

export const MONDAY_HOURS_COUNT = "MONDAY_HOURS_COUNT";

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
